blank_issues_enabled: false
contact_links:
  - name: DO Access 
    url: https://sd.suse.com/servicedesk/customer/portal/1
    about: PDigitial Ocean cloud platform
  - name: GitHub Security Bug Bounty
    url: https://bounty.github.com/
    about: Please report security vulnerabilities here.
